<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UbigeoProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ubigeo_province')->insert([
            ['id_prov' => 1, 'province' => 'CHACHAPOYAS', 'id_depa' => 1],
            ['id_prov' => 2, 'province' => 'BAGUA', 'id_depa' => 1],
            ['id_prov' => 3, 'province' => 'BONGARA', 'id_depa' => 1],
            ['id_prov' => 4, 'province' => 'CONDORCANQUI', 'id_depa' => 1],
            ['id_prov' => 5, 'province' => 'LUYA', 'id_depa' => 1],
            ['id_prov' => 6, 'province' => 'RODRIGUEZ DE MENDOZA', 'id_depa' => 1],
            ['id_prov' => 7, 'province' => 'UTCUBAMBA', 'id_depa' => 1],
            ['id_prov' => 8, 'province' => 'HUARAZ', 'id_depa' => 2],
            ['id_prov' => 9, 'province' => 'AIJA', 'id_depa' => 2],
            ['id_prov' => 10, 'province' => 'ANTONIO RAYMONDI', 'id_depa' => 2],
            ['id_prov' => 11, 'province' => 'ASUNCION', 'id_depa' => 2],
            ['id_prov' => 12, 'province' => 'BOLOGNESI', 'id_depa' => 2],
            ['id_prov' => 13, 'province' => 'CARHUAZ', 'id_depa' => 2],
            ['id_prov' => 14, 'province' => 'CARLOS FERMIN FITZCARRALD', 'id_depa' => 2],
            ['id_prov' => 15, 'province' => 'CASMA', 'id_depa' => 2],
            ['id_prov' => 16, 'province' => 'CORONGO', 'id_depa' => 2],
            ['id_prov' => 17, 'province' => 'HUARI', 'id_depa' => 2],
            ['id_prov' => 18, 'province' => 'HUARMEY', 'id_depa' => 2],
            ['id_prov' => 19, 'province' => 'HUAYLAS', 'id_depa' => 2],
            ['id_prov' => 20, 'province' => 'MARISCAL LUZURIAGA', 'id_depa' => 2],
            ['id_prov' => 21, 'province' => 'OCROS', 'id_depa' => 2],
            ['id_prov' => 22, 'province' => 'PALLASCA', 'id_depa' => 2],
            ['id_prov' => 23, 'province' => 'POMABAMBA', 'id_depa' => 2],
            ['id_prov' => 24, 'province' => 'RECUAY', 'id_depa' => 2],
            ['id_prov' => 25, 'province' => 'SANTA', 'id_depa' => 2],
            ['id_prov' => 26, 'province' => 'SIHUAS', 'id_depa' => 2],
            ['id_prov' => 27, 'province' => 'YUNGAY', 'id_depa' => 2],
            ['id_prov' => 28, 'province' => 'ABANCAY', 'id_depa' => 3],
            ['id_prov' => 29, 'province' => 'ANDAHUAYLAS', 'id_depa' => 3],
            ['id_prov' => 30, 'province' => 'ANTABAMBA', 'id_depa' => 3],
            ['id_prov' => 31, 'province' => 'AYMARAES', 'id_depa' => 3],
            ['id_prov' => 32, 'province' => 'COTABAMBAS', 'id_depa' => 3],
            ['id_prov' => 33, 'province' => 'CHINCHEROS', 'id_depa' => 3],
            ['id_prov' => 34, 'province' => 'GRAU', 'id_depa' => 3],
            ['id_prov' => 35, 'province' => 'AREQUIPA', 'id_depa' => 4],
            ['id_prov' => 36, 'province' => 'CAMANA', 'id_depa' => 4],
            ['id_prov' => 37, 'province' => 'CARAVELI', 'id_depa' => 4],
            ['id_prov' => 38, 'province' => 'CASTILLA', 'id_depa' => 4],
            ['id_prov' => 39, 'province' => 'CAYLLOMA', 'id_depa' => 4],
            ['id_prov' => 40, 'province' => 'CONDESUYOS', 'id_depa' => 4],
            ['id_prov' => 41, 'province' => 'ISLAY', 'id_depa' => 4],
            ['id_prov' => 42, 'province' => 'LA UNION', 'id_depa' => 4],
            ['id_prov' => 43, 'province' => 'HUAMANGA', 'id_depa' => 5],
            ['id_prov' => 44, 'province' => 'CANGALLO', 'id_depa' => 5],
            ['id_prov' => 45, 'province' => 'HUANCA SANCOS', 'id_depa' => 5],
            ['id_prov' => 46, 'province' => 'HUANTA', 'id_depa' => 5],
            ['id_prov' => 47, 'province' => 'LA MAR', 'id_depa' => 5],
            ['id_prov' => 48, 'province' => 'LUCANAS', 'id_depa' => 5],
            ['id_prov' => 49, 'province' => 'PARINACOCHAS', 'id_depa' => 5],
            ['id_prov' => 50, 'province' => 'PAUCAR DEL SARA SARA', 'id_depa' => 5],
            ['id_prov' => 51, 'province' => 'SUCRE', 'id_depa' => 5],
            ['id_prov' => 52, 'province' => 'VICTOR FAJARDO', 'id_depa' => 5],
            ['id_prov' => 53, 'province' => 'VILCAS HUAMAN', 'id_depa' => 5],
            ['id_prov' => 54, 'province' => 'CAJAMARCA', 'id_depa' => 6],
            ['id_prov' => 55, 'province' => 'CAJABAMBA', 'id_depa' => 6],
            ['id_prov' => 56, 'province' => 'CELENDIN', 'id_depa' => 6],
            ['id_prov' => 57, 'province' => 'CHOTA', 'id_depa' => 6],
            ['id_prov' => 58, 'province' => 'CONTUMAZA', 'id_depa' => 6],
            ['id_prov' => 59, 'province' => 'CUTERVO', 'id_depa' => 6],
            ['id_prov' => 60, 'province' => 'HUALGAYOC', 'id_depa' => 6],
            ['id_prov' => 61, 'province' => 'JAEN', 'id_depa' => 6],
            ['id_prov' => 62, 'province' => 'SAN IGNACIO', 'id_depa' => 6],
            ['id_prov' => 63, 'province' => 'SAN MARCOS', 'id_depa' => 6],
            ['id_prov' => 64, 'province' => 'SAN PABLO', 'id_depa' => 6],
            ['id_prov' => 65, 'province' => 'SANTA CRUZ', 'id_depa' => 6],
            ['id_prov' => 66, 'province' => 'CALLAO', 'id_depa' => 7],
            ['id_prov' => 67, 'province' => 'CUSCO', 'id_depa' => 8],
            ['id_prov' => 68, 'province' => 'ACOMAYO', 'id_depa' => 8],
            ['id_prov' => 69, 'province' => 'ANTA', 'id_depa' => 8],
            ['id_prov' => 70, 'province' => 'CALCA', 'id_depa' => 8],
            ['id_prov' => 71, 'province' => 'CANAS', 'id_depa' => 8],
            ['id_prov' => 72, 'province' => 'CANCHIS', 'id_depa' => 8],
            ['id_prov' => 73, 'province' => 'CHUMBIVILCAS', 'id_depa' => 8],
            ['id_prov' => 74, 'province' => 'ESPINAR', 'id_depa' => 8],
            ['id_prov' => 75, 'province' => 'LA CONVENCION', 'id_depa' => 8],
            ['id_prov' => 76, 'province' => 'PARURO', 'id_depa' => 8],
            ['id_prov' => 77, 'province' => 'PAUCARTAMBO', 'id_depa' => 8],
            ['id_prov' => 78, 'province' => 'QUISPICANCHI', 'id_depa' => 8],
            ['id_prov' => 79, 'province' => 'URUBAMBA', 'id_depa' => 8],
            ['id_prov' => 80, 'province' => 'HUANCAVELICA', 'id_depa' => 9],

            /**************************************************************/

            ['id_prov' => 81, 'province' => 'ACOBAMBA', 'id_depa' => 9],
            ['id_prov' => 82, 'province' => 'ANGARAES', 'id_depa' => 9],
            ['id_prov' => 83, 'province' => 'CASTROVIRREYNA', 'id_depa' => 9],
            ['id_prov' => 84, 'province' => 'CHURCAMPA', 'id_depa' => 9],
            ['id_prov' => 85, 'province' => 'HUAYTARA', 'id_depa' => 9],
            ['id_prov' => 86, 'province' => 'TAYACAJA', 'id_depa' => 9],
            ['id_prov' => 87, 'province' => 'HUANUCO', 'id_depa' => 10],
            ['id_prov' => 88, 'province' => 'AMBO', 'id_depa' => 10],
            ['id_prov' => 89, 'province' => 'DOS DE MAYO', 'id_depa' => 10],
            ['id_prov' => 90, 'province' => 'HUACAYBAMBA', 'id_depa' => 10],
            ['id_prov' => 91, 'province' => 'HUAMALIES', 'id_depa' => 10],
            ['id_prov' => 92, 'province' => 'LEONCIO PRADO', 'id_depa' => 10],
            ['id_prov' => 93, 'province' => 'MARAÑON', 'id_depa' => 10],
            ['id_prov' => 94, 'province' => 'PACHITEA', 'id_depa' => 10],
            ['id_prov' => 95, 'province' => 'PUERTO INCA', 'id_depa' => 10],
            ['id_prov' => 96, 'province' => 'LAURICOCHA', 'id_depa' => 10],
            ['id_prov' => 97, 'province' => 'YAROWILCA', 'id_depa' => 10],
            ['id_prov' => 98, 'province' => 'ICA', 'id_depa' => 11],
            ['id_prov' => 99, 'province' => 'CHINCHA', 'id_depa' => 11],
            ['id_prov' => 100, 'province' => 'NAZCA', 'id_depa' => 11],
            ['id_prov' => 101, 'province' => 'PALPA', 'id_depa' => 11],
            ['id_prov' => 102, 'province' => 'PISCO', 'id_depa' => 11],
            ['id_prov' => 103, 'province' => 'HUANCAYO', 'id_depa' => 12],
            ['id_prov' => 104, 'province' => 'CONCEPCION', 'id_depa' => 12],
            ['id_prov' => 105, 'province' => 'CHANCHAMAYO', 'id_depa' => 12],
            ['id_prov' => 106, 'province' => 'JAUJA', 'id_depa' => 12],
            ['id_prov' => 107, 'province' => 'JUNIN', 'id_depa' => 12],
            ['id_prov' => 108, 'province' => 'SATIPO', 'id_depa' => 12],
            ['id_prov' => 109, 'province' => 'TARMA', 'id_depa' => 12],
            ['id_prov' => 110, 'province' => 'YAULI', 'id_depa' => 12],
            ['id_prov' => 111, 'province' => 'CHUPACA', 'id_depa' => 12],
            ['id_prov' => 112, 'province' => 'TRUJILLO', 'id_depa' => 13],
            ['id_prov' => 113, 'province' => 'ASCOPE', 'id_depa' => 13],
            ['id_prov' => 114, 'province' => 'BOLIVAR', 'id_depa' => 13],
            ['id_prov' => 115, 'province' => 'CHEPEN', 'id_depa' => 13],
            ['id_prov' => 116, 'province' => 'JULCAN', 'id_depa' => 13],
            ['id_prov' => 117, 'province' => 'OTUZCO', 'id_depa' => 13],
            ['id_prov' => 118, 'province' => 'PACASMAYO', 'id_depa' => 13],
            ['id_prov' => 119, 'province' => 'PATAZ', 'id_depa' => 13],
            ['id_prov' => 120, 'province' => 'SANCHEZ CARRION', 'id_depa' => 13],
            ['id_prov' => 121, 'province' => 'SANTIAGO DE CHUCO', 'id_depa' => 13],
            ['id_prov' => 122, 'province' => 'GRAN CHIMU', 'id_depa' => 13],
            ['id_prov' => 123, 'province' => 'VIRU', 'id_depa' => 13],
            ['id_prov' => 124, 'province' => 'CHICLAYO', 'id_depa' => 14],
            ['id_prov' => 125, 'province' => 'FERREÑAFE', 'id_depa' => 14],
            ['id_prov' => 126, 'province' => 'LAMBAYEQUE', 'id_depa' => 14],
            ['id_prov' => 127, 'province' => 'LIMA', 'id_depa' => 15],
            ['id_prov' => 128, 'province' => 'BARRANCA', 'id_depa' => 15],
            ['id_prov' => 129, 'province' => 'CAJATAMBO', 'id_depa' => 15],
            ['id_prov' => 130, 'province' => 'CANTA', 'id_depa' => 15],
            ['id_prov' => 131, 'province' => 'CAÑETE', 'id_depa' => 15],
            ['id_prov' => 132, 'province' => 'HUARAL', 'id_depa' => 15],
            ['id_prov' => 133, 'province' => 'HUAROCHIRI', 'id_depa' => 15],
            ['id_prov' => 134, 'province' => 'HUAURA', 'id_depa' => 15],
            ['id_prov' => 135, 'province' => 'OYON', 'id_depa' => 15],
            ['id_prov' => 136, 'province' => 'YAUYOS', 'id_depa' => 15],
            ['id_prov' => 137, 'province' => 'MAYNAS', 'id_depa' => 16],
            ['id_prov' => 138, 'province' => 'ALTO AMAZONAS', 'id_depa' => 16],
            ['id_prov' => 139, 'province' => 'LORETO', 'id_depa' => 16],
            ['id_prov' => 140, 'province' => 'MARISCAL RAMON CASTILLA', 'id_depa' => 16],
            ['id_prov' => 141, 'province' => 'REQUENA', 'id_depa' => 16],
            ['id_prov' => 142, 'province' => 'UCAYALI', 'id_depa' => 16],
            ['id_prov' => 143, 'province' => 'TAMBOPATA', 'id_depa' => 17],
            ['id_prov' => 144, 'province' => 'MANU', 'id_depa' => 17],
            ['id_prov' => 145, 'province' => 'TAHUAMANU', 'id_depa' => 17],
            ['id_prov' => 146, 'province' => 'MARISCAL NIETO', 'id_depa' => 18],
            ['id_prov' => 147, 'province' => 'GENERAL SANCHEZ CERRO', 'id_depa' => 18],
            ['id_prov' => 148, 'province' => 'ILO', 'id_depa' => 18],
            ['id_prov' => 149, 'province' => 'PASCO', 'id_depa' => 19],
            ['id_prov' => 150, 'province' => 'DANIEL ALCIDES CARRION', 'id_depa' => 19],
            ['id_prov' => 151, 'province' => 'OXAPAMPA', 'id_depa' => 19],
            ['id_prov' => 152, 'province' => 'PIURA', 'id_depa' => 20],
            ['id_prov' => 153, 'province' => 'AYABACA', 'id_depa' => 20],
            ['id_prov' => 154, 'province' => 'HUANCABAMBA', 'id_depa' => 20],
            ['id_prov' => 155, 'province' => 'MORROPON', 'id_depa' => 20],
            ['id_prov' => 156, 'province' => 'PAITA', 'id_depa' => 20],
            ['id_prov' => 157, 'province' => 'SULLANA', 'id_depa' => 20],
            ['id_prov' => 158, 'province' => 'TALARA', 'id_depa' => 20],
            ['id_prov' => 159, 'province' => 'SECHURA', 'id_depa' => 20],
            ['id_prov' => 160, 'province' => 'PUNO', 'id_depa' => 21],

            /**************************************************************/

            ['id_prov' => 161, 'province' => 'AZANGARO', 'id_depa' => 21],
            ['id_prov' => 162, 'province' => 'CARABAYA', 'id_depa' => 21],
            ['id_prov' => 163, 'province' => 'CHUCUITO', 'id_depa' => 21],
            ['id_prov' => 164, 'province' => 'EL COLLAO', 'id_depa' => 21],
            ['id_prov' => 165, 'province' => 'HUANCANE', 'id_depa' => 21],
            ['id_prov' => 166, 'province' => 'LAMPA', 'id_depa' => 21],
            ['id_prov' => 167, 'province' => 'MELGAR', 'id_depa' => 21],
            ['id_prov' => 168, 'province' => 'MOHO', 'id_depa' => 21],
            ['id_prov' => 169, 'province' => 'SAN ANTONIO DE PUTINA', 'id_depa' => 21],
            ['id_prov' => 170, 'province' => 'SAN ROMAN', 'id_depa' => 21],
            ['id_prov' => 171, 'province' => 'SANDIA', 'id_depa' => 21],
            ['id_prov' => 172, 'province' => 'YUNGUYO', 'id_depa' => 21],
            ['id_prov' => 173, 'province' => 'MOYOBAMBA', 'id_depa' => 22],
            ['id_prov' => 174, 'province' => 'BELLAVISTA', 'id_depa' => 22],
            ['id_prov' => 175, 'province' => 'EL DORADO', 'id_depa' => 22],
            ['id_prov' => 176, 'province' => 'HUALLAGA', 'id_depa' => 22],
            ['id_prov' => 177, 'province' => 'LAMAS', 'id_depa' => 22],
            ['id_prov' => 178, 'province' => 'MARISCAL CACERES', 'id_depa' => 22],
            ['id_prov' => 179, 'province' => 'PICOTA', 'id_depa' => 22],
            ['id_prov' => 180, 'province' => 'RIOJA', 'id_depa' => 22],
            ['id_prov' => 181, 'province' => 'SAN MARTIN', 'id_depa' => 22],
            ['id_prov' => 182, 'province' => 'TOCACHE', 'id_depa' => 22],
            ['id_prov' => 183, 'province' => 'TACNA', 'id_depa' => 23],
            ['id_prov' => 184, 'province' => 'CANDARAVE', 'id_depa' => 23],
            ['id_prov' => 185, 'province' => 'JORGE BASADRE', 'id_depa' => 23],
            ['id_prov' => 186, 'province' => 'TARATA', 'id_depa' => 23],
            ['id_prov' => 187, 'province' => 'TUMBES', 'id_depa' => 24],
            ['id_prov' => 188, 'province' => 'CONTRALMIRANTE VILLAR', 'id_depa' => 24],
            ['id_prov' => 189, 'province' => 'ZARUMILLA', 'id_depa' => 24],
            ['id_prov' => 190, 'province' => 'CORONEL PORTILLO', 'id_depa' => 25],
            ['id_prov' => 191, 'province' => 'ATALAYA', 'id_depa' => 25],
            ['id_prov' => 192, 'province' => 'PADRE ABAD', 'id_depa' => 25],
            ['id_prov' => 193, 'province' => 'PURUS', 'id_depa' => 25],
        ]);
    }
}
